// Auto-generated WebForms designer file.
// Regenerated by Visual Studio whenever Default.aspx markup is saved.
namespace LegacyShell
{
    public partial class DefaultPage
    {
        protected global::System.Web.UI.WebControls.Panel      PnlLogin;
        protected global::System.Web.UI.WebControls.Panel      PnlShell;
        protected global::System.Web.UI.WebControls.Label      LblError;
        protected global::System.Web.UI.WebControls.TextBox    TxtUsername;
        protected global::System.Web.UI.WebControls.TextBox    TxtPassword;
        protected global::System.Web.UI.WebControls.Button     BtnLogin;
        protected global::System.Web.UI.WebControls.Label      lblUser;
        protected global::System.Web.UI.WebControls.LinkButton BtnLogout;
        protected global::System.Web.UI.WebControls.Literal    LitJwtScript;
    }
}
